### ISSUE TITLE
Day agenda not updating when changing dates

### ISSUE THREAD

**Issue by mathiask** [apps-evolve-summit/summit-app#1]
I get the following errors in the console:

Chrome:

polymer-mini.html:2055 Uncaught TypeError: Cannot read property 'name' of undefined
    at HTMLElement._getRoomName (time-schedule-page.html:325)
    at TemplateInstance._annotatedComputationEffect (polymer.html:1698)
    at TemplateInstance._effectEffects (polymer.html:1507)
    at TemplateInstance._propertySetter (polymer.html:1491)
    at TemplateInstance.__setProperty [as __setPropertyOrig] (polymer.html:1500)
    at TemplateInstance.__setPropertyImpl [as __setProperty] (polymer.html:4355)
    at HTMLTemplateElement._forwardParentProp (polymer.html:5363)
    at HTMLTemplateElement.<anonymous> (polymer.html:4437)
    at HTMLTemplateElement._functionEffect (polymer.html:1657)
    at HTMLTemplateElement._effectEffects (polymer.html:1507)

Firefox:
TypeError: eventData.rooms.filter(...)[0] is undefined[Learn More] data:%0A%0A%20%20%20%20(function()%20%7B%0A%0A%20%20%20%20%20%20var%20SHORT_DESC_MAX%20%3D%2050%3B%0:109:1
	._getRoomName http://localhost:8888/src/time-schedule-page.html.js:109:1
	._annotatedComputationEffect http://localhost:8888/bower_components/polymer/polymer.html.js:1682:21
	Polymer.Bind._modelApi._effectEffects http://localhost:8888/bower_components/polymer/polymer.html.js:1491:1
	Polymer.Bind._modelApi._propertySetter http://localhost:8888/bower_components/polymer/polymer.html.js:1475:1
	Polymer.Bind._modelApi.__setProperty http://localhost:8888/bower_components/polymer/polymer.html.js:1484:1
	Polymer.Templatizer.__setPropertyImpl http://localhost:8888/bower_components/polymer/polymer.html.js:4339:1
	._forwardParentProp http://localhost:8888/bower_components/polymer/polymer.html.js:5347:1
	Polymer.Templatizer._createForwardPropEffector/< http://localhost:8888/bower_components/polymer/polymer.html.js:4421:1
	._functionEffect http://localhost:8888/bower_components/polymer/polymer.html.js:1641:1
	Polymer.Bind._modelApi._effectEffects http://localhost:8888/bower_components/polymer/polymer.html.js:1491:1
	Polymer.Bind._modelApi._propertySetter http://localhost:8888/bower_components/polymer/polymer.html.js:1475:1
	Polymer.Bind._modelApi.__setProperty http://localhost:8888/bower_components/polymer/polymer.html.js:1484:1
	Polymer.Templatizer.__setPropertyImpl http://localhost:8888/bower_components/polymer/polymer.html.js:4339:1
	._applyEffectValue http://localhost:8888/bower_components/polymer/polymer.html.js:1967:1
	._annotationEffect http://localhost:8888/bower_components/polymer/polymer.html.js:1630:1
	Polymer.Bind._modelApi._effectEffects http://localhost:8888/bower_components/polymer/polymer.html.js:1491:1
	Polymer.Bind._modelApi._propertySetter http://localhost:8888/bower_components/polymer/polymer.html.js:1475:1
	Polymer.Bind._createAccessors/setter http://localhost:8888/bower_components/polymer/polymer.html.js:1554:1
	._assignModels/< http://localhost:8888/bower_components/iron-list/iron-list.html.js:1015:11
	._iterateItems http://localhost:8888/bower_components/iron-list/iron-list.html.js:980:22
	._assignModels http://localhost:8888/bower_components/iron-list/iron-list.html.js:1010:7
	._update http://localhost:8888/bower_components/iron-list/iron-list.html.js:660:7
	._render http://localhost:8888/bower_components/iron-list/iron-list.html.js:779:11
	Polymer.Debounce</Debouncer.prototype.complete http://localhost:8888/bower_components/polymer/polymer-mini.html.js:2086:1
	Polymer.Debounce</Debouncer/this.boundComplete http://localhost:8888/bower_components/polymer/polymer-mini.html.js:2063:1
	Polymer.Async._atEndOfMicrotask http://localhost:8888/bower_components/polymer/polymer-mini.html.js:2041:1
	<anonymous> http://localhost:8888/bower_components/polymer/polymer-mini.html.js:2056:1

**Comment by dumbNickname** [comment]
Hey,

Yesterday I forgot to push changes to github. Those should be there now, please check if it works fine for you now (hard browser refresh needed as service workers use same cache name).

**Comment by mathiask** [comment]
I had an old version (16 March 2017). The problem no longer exists in the current master branch.

**Comment by mathiask** [comment]
Hi Bartek,

I just saw that on Github. Everything is working fine and I closed the issue. 

Regards,
Mathias
